version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    env_file:
      - ./.env
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload